In [2]:
!pip install -q -U watermark

In [3]:
!pip install -q plotly

In [64]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import plotly
import matplotlib.pyplot as plt
import plotly.offline as pyoff
import plotly.graph_objs as go
from datetime import datetime, timedelta
%matplotlib inline
pyoff.init_notebook_mode

In [65]:
%reload_ext watermark
%watermark -a "Diego Oliveira" --iversions

Author: Diego Oliveira

matplotlib: 3.2.2
IPython   : 5.5.0
pandas    : 1.3.5
plotly    : 5.5.0
numpy     : 1.21.5
seaborn   : 0.11.2

In [66]:
dados = pd.read_csv("dataset.csv", header = 0, encoding = "unicode_escape")

In [67]:
dados.head()

,NumeroFatura,CodigoProduto,NomeProduto,Quantidade,DataVenda,ValorUnitario,IdCliente,Pais
0,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,Brasil
1,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,Brasil
2,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,Brasil
3,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,Brasil
4,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,Brasil

In [68]:
dados.shape

(541800, 8)

In [69]:
dados.dtypes

NumeroFatura      object
CodigoProduto     object
NomeProduto       object
Quantidade         int64
DataVenda         object
ValorUnitario    float64
IdCliente        float64
Pais              object
dtype: object

In [70]:
dados.describe()

          Quantidade  ValorUnitario      IdCliente
count  541800.000000  541800.000000  406725.000000
mean        9.551739       4.611581   15287.754038
std       218.103033      96.769576    1713.475925
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13954.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [71]:
dados.isna().sum()

NumeroFatura          0
CodigoProduto         0
NomeProduto        1454
Quantidade            0
DataVenda             0
ValorUnitario         0
IdCliente        135075
Pais                  0
dtype: int64

In [72]:
print("Data mínina: ", dados["DataVenda"].min())
print("Data Máxima: ", dados["DataVenda"].max())

Data mínina:  1/10/2011 10:04
Data Máxima:  9/9/2011 9:52

In [73]:
dados.DataVenda = pd.to_datetime(dados.DataVenda)

In [74]:
dados.dtypes

NumeroFatura             object
CodigoProduto            object
NomeProduto              object
Quantidade                int64
DataVenda        datetime64[ns]
ValorUnitario           float64
IdCliente               float64
Pais                     object
dtype: object

In [75]:
print("Data mínina: ", dados["DataVenda"].min())
print("Data Máxima: ", dados["DataVenda"].max())

Data mínina:  2010-12-01 08:26:00
Data Máxima:  2011-12-09 12:50:00

In [76]:
dados["Pais"].unique()

array(['Brasil', 'Uruguai', 'Australia', 'Holanda', 'Alemanha', 'Noruega',
       'Irlanda', 'Espanha', 'Poland', 'Portugal', 'Italy', 'Belgium',
       'Lithuania', 'Japan', 'Iceland', 'Channel Islands', 'Dinamarca',
       'Cyprus', 'Sweden', 'Austria', 'Israel', 'Finland', 'Bahrain',
       'Greece', 'Hong Kong', 'Cingapura', 'Iraque', 'Equador',
       'Saudi Arabia', 'Czech Republic', 'Canada', 'China', 'Inglaterra',
       'USA', 'Chile', 'Malta', 'Paraguai'], dtype=object)

In [77]:
dados.dtypes

NumeroFatura             object
CodigoProduto            object
NomeProduto              object
Quantidade                int64
DataVenda        datetime64[ns]
ValorUnitario           float64
IdCliente               float64
Pais                     object
dtype: object

In [78]:
dados["AnoMes"] = dados["DataVenda"].map(lambda date: 100 * date.year + date.month)

In [79]:
dados.head()

,NumeroFatura,CodigoProduto,NomeProduto,Quantidade,DataVenda,ValorUnitario,IdCliente,Pais,AnoMes
0,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,Brasil,201012
1,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,Brasil,201012
2,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,Brasil,201012
3,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,Brasil,201012
4,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,Brasil,201012

In [80]:
dados["Faturamento"] = dados["Quantidade"] * dados["ValorUnitario"]

In [81]:
dados.head()

,NumeroFatura,CodigoProduto,NomeProduto,Quantidade,DataVenda,ValorUnitario,IdCliente,Pais,AnoMes,Faturamento
0,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,Brasil,201012,25.50
1,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,Brasil,201012,15.30
2,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,Brasil,201012,20.34
3,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,Brasil,201012,22.00
4,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,Brasil,201012,20.34

In [82]:
df_faturamento = dados.groupby(['AnoMes']).agg({'Faturamento': sum}).reset_index()

In [83]:
df_faturamento

    AnoMes  Faturamento
0   201012   748957.020
1   201101   560000.260
2   201102   498062.650
3   201103   683267.080
4   201104   493207.121
5   201105   723333.510
6   201106   691123.120
7   201107   681300.111
8   201108   682680.510
9   201109  1019687.622
10  201110  1070704.670
11  201111  1461756.250
12  201112   431245.000

In [84]:
df_faturamento["Crescimento"] = df_faturamento["Faturamento"].pct_change()

In [85]:
df_faturamento.head()

   AnoMes  Faturamento  Crescimento
0  201012   748957.020          NaN
1  201101   560000.260    -0.252293
2  201102   498062.650    -0.110603
3  201103   683267.080     0.371850
4  201104   493207.121    -0.278163

In [86]:
plot_data = [go.Scatter(x = df_faturamento['AnoMes'], 
                        y = df_faturamento['Faturamento'],)]

plot_layout = go.Layout(xaxis = {"type": "category"}, 
                        title = 'Faturamento Mensal')

fig = go.Figure(data = plot_data, layout = plot_layout)
pyoff.iplot(fig)

In [89]:
dados_brasil = dados.query("Pais == 'Brasil'").reset_index(drop = True)

In [90]:
df_ativo_mes = dados_brasil.groupby("AnoMes")["IdCliente"].nunique().reset_index()

In [91]:
df_ativo_mes

    AnoMes  IdCliente
0   201012        871
1   201101        684
2   201102        714
3   201103        923
4   201104        817
5   201105        985
6   201106        943
7   201107        899
8   201108        867
9   201109       1177
10  201110       1285
11  201111       1548
12  201112        614

In [92]:
plot_data = [go.Bar(x = df_ativo_mes["AnoMes"],
                    y = df_ativo_mes["IdCliente"],)]
plot_layout = go.Layout(xaxis = {"type": "category"},
                        title = "Clientes ativos por mês no Brasil")
fig = go.Figure(data = plot_data, layout = plot_layout)
pyoff.iplot(fig)

In [93]:
df_itens_mes = dados_brasil.groupby("AnoMes")["Quantidade"].sum().reset_index()

In [94]:
df_itens_mes

    AnoMes  Quantidade
0   201012      298101
1   201101      237381
2   201102      225641
3   201103      279843
4   201104      257666
5   201105      306452
6   201106      258522
7   201107      324129
8   201108      319804
9   201109      458490
10  201110      455612
11  201111      642281
12  201112      198750

In [95]:
plot_data = [go.Bar(x = df_itens_mes["AnoMes"],
                    y = df_itens_mes["Quantidade"],)]
plot_layout= go.Layout(xaxis =  {"type": "category"},
                       title = "Itens comprados por mês no Brasil")
fig = go.Figure(data = plot_data, layout = plot_layout)
pyoff.iplot(fig)

In [96]:
df_faturamento_medio = dados_brasil.groupby("AnoMes")["Faturamento"].mean().reset_index()

In [97]:
df_faturamento_medio

    AnoMes  Faturamento
0   201012    16.865860
1   201101    13.614680
2   201102    16.093027
3   201103    16.716166
4   201104    15.773380
5   201105    17.713823
6   201106    16.714748
7   201107    15.723497
8   201108    17.315899
9   201109    18.931723
10  201110    16.093582
11  201111    16.312383
12  201112    16.223363

In [98]:
plt_data = [go.Bar(x = df_faturamento_medio["AnoMes"],
                   y = df_faturamento_medio["Faturamento"],)]
plot_layout = go.Layout(xaxis = {"type": "category"},
                        title = "Faturamento medio mensal no Brasil")
fig = go.Figure(data = plot_data, layout = plot_layout)
pyoff.iplot(fig)

In [99]:
df_faturamento_total = dados_brasil.groupby("AnoMes")["Faturamento"].sum().reset_index()

In [100]:
df_faturamento_total

    AnoMes  Faturamento
0   201012   676742.620
1   201101   434308.300
2   201102   408247.910
3   201103   559707.390
4   201104   442254.041
5   201105   596459.860
6   201106   554478.350
7   201107   565479.841
8   201108   539130.500
9   201109   862018.152
10  201110   877438.190
11  201111  1282805.780
12  201112   386651.410

In [103]:
plot_data = [go.Bar(x = df_faturamento_total['AnoMes'], 
                    y = df_faturamento_total['Faturamento'],)]

plot_layout = go.Layout(xaxis = {"type": "category"}, 
                        title = 'Faturamento Total Mensal em um País (Brasil)')

fig = go.Figure(data = plot_data, layout = plot_layout)
pyoff.iplot(fig)

In [104]:
df_compra_minima = dados.groupby("IdCliente")["DataVenda"].min().reset_index()

In [105]:
df_compra_minima.columns = ["IdCliente", "Data_Menor_Compra"]

In [107]:
df_compra_minima['Mes_Menor_Compra_Mensal'] = df_compra_minima['Data_Menor_Compra'].map(lambda date: 100 * date.year + date.month)

In [109]:
df_compra_minima.head()

   IdCliente   Data_Menor_Compra  Mes_Menor_Compra_Mensal
0    12346.0 2011-01-18 10:01:00                   201101
1    12347.0 2010-12-07 14:57:00                   201012
2    12348.0 2010-12-16 19:09:00                   201012
3    12349.0 2011-11-21 09:51:00                   201111
4    12350.0 2011-02-02 16:01:00                   201102

In [110]:
dados_compras = pd.merge(dados, df_compra_minima, on = "IdCliente")
dados_compras.head()

,NumeroFatura,CodigoProduto,NomeProduto,Quantidade,DataVenda,ValorUnitario,IdCliente,Pais,AnoMes,Faturamento,Data_Menor_Compra,Mes_Menor_Compra_Mensal
0,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,Brasil,201012,25.50,2010-12-01 08:26:00,201012
1,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,Brasil,201012,15.30,2010-12-01 08:26:00,201012
2,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,Brasil,201012,20.34,2010-12-01 08:26:00,201012
3,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,Brasil,201012,22.00,2010-12-01 08:26:00,201012
4,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,Brasil,201012,20.34,2010-12-01 08:26:00,201012

In [111]:
dados_compras["TipoUsuario"] = "Novo"

In [113]:
dados_compras["TipoUsuario"].value_counts()

Novo    406725
Name: TipoUsuario, dtype: int64

In [114]:
dados_compras.head()

,NumeroFatura,CodigoProduto,NomeProduto,Quantidade,DataVenda,ValorUnitario,IdCliente,Pais,AnoMes,Faturamento,Data_Menor_Compra,Mes_Menor_Compra_Mensal,TipoUsuario
0,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,Brasil,201012,25.50,2010-12-01 08:26:00,201012,Novo
1,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,Brasil,201012,15.30,2010-12-01 08:26:00,201012,Novo
2,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,Brasil,201012,20.34,2010-12-01 08:26:00,201012,Novo
3,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,Brasil,201012,22.00,2010-12-01 08:26:00,201012,Novo
4,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,Brasil,201012,20.34,2010-12-01 08:26:00,201012,Novo

In [116]:
dados_compras.loc[dados_compras["AnoMes"] > dados_compras["Mes_Menor_Compra_Mensal"], "TipoUsuario"] = "Antigo"

In [118]:
df_faturamento_user_mes = dados_compras.groupby(['AnoMes', 'TipoUsuario'])['Faturamento'].sum().reset_index()

In [120]:
df_faturamento_user_mes = df_faturamento_user_mes.query("AnoMes != 201012 and AnoMes != 201112")

In [121]:
df_faturamento_user_mes

    AnoMes TipoUsuario  Faturamento
1   201101      Antigo   271616.520
2   201101        Novo   203457.860
3   201102      Antigo   287024.770
4   201102        Novo   149521.380
5   201103      Antigo   390034.530
6   201103        Novo   189930.080
7   201104      Antigo   306283.600
8   201104        Novo   119764.251
9   201105      Antigo   532392.340
10  201105        Novo   115858.740
11  201106      Antigo   515486.650
12  201106        Novo    92526.510
13  201107      Antigo   508355.610
14  201107        Novo    65882.871
15  201108      Antigo   538709.770
16  201108        Novo    77658.230
17  201109      Antigo   778161.781
18  201109        Novo   153278.591
19  201110      Antigo   819672.900
20  201110        Novo   154930.690
21  201111      Antigo   998176.360
22  201111        Novo   134231.380

In [122]:
plot_data = [go.Scatter(x = df_faturamento_user_mes.query("TipoUsuario == 'Antigo'")["AnoMes"],
                        y = df_faturamento_user_mes.query("TipoUsuario == 'Antigo'")["Faturamento"],
                        name = "Cliente Antigo"),
             go.Scatter(x = df_faturamento_user_mes.query("TipoUsuario == 'Novo'")["AnoMes"],
                        y = df_faturamento_user_mes.query("TipoUsuario == 'Novo'")["Faturamento"],
                        name = "Cliente Novo")]
plot_layout = go.Layout(xaxis = {"type": "category"},
                        title = "Diferença faturamento ao longo do tempo entre clientes antigos e novos")
fig = go.Figure(data = plot_data, layout = plot_layout)
pyoff.iplot(fig)

In [124]:
df_taxa_novos_clientes = dados_compras.query("TipoUsuario == 'Novo'").groupby(['AnoMes'])['IdCliente'].nunique() / dados_compras.query("TipoUsuario == 'Antigo'").groupby(['AnoMes'])['IdCliente'].nunique()

In [125]:
df_taxa_novos_clientes = df_taxa_novos_clientes.reset_index()
df_taxa_novos_clientes = df_taxa_novos_clientes.dropna()

In [126]:
df_taxa_novos_clientes

    AnoMes  IdCliente
1   201101   1.162983
2   201102   0.909091
3   201103   0.758621
4   201104   0.498333
5   201105   0.348750
6   201106   0.287990
7   201107   0.238155
8   201108   0.205412
9   201109   0.296813
10  201110   0.328052
11  201111   0.230935
12  201112   0.063863

In [127]:
plot_data = [go.Bar(x = df_taxa_novos_clientes.query("AnoMes > 201101 and AnoMes < 201112")["AnoMes"],
                    y = df_taxa_novos_clientes.query("AnoMes > 201101 and AnoMes < 201112")["IdCliente"],)]
plot_layout = go.Layout(xaxis = {"type": "category"},
                        title = "Taxa novos clientes")
fig = go.Figure(data = plot_data, layout = plot_layout)
pyoff.iplot(fig)

In [128]:
dados_compras_clientes = dados_compras.groupby(["IdCliente","AnoMes"])["Faturamento"].sum().reset_index()

In [130]:
dados_compras_clientes.head()

   IdCliente  AnoMes  Faturamento
0    12346.0  201101         0.00
1    12347.0  201012       711.79
2    12347.0  201101       475.39
3    12347.0  201104       636.25
4    12347.0  201106       382.52

In [131]:
df_ret = pd.crosstab(dados_compras_clientes["IdCliente"], dados_compras_clientes["AnoMes"]).reset_index()

In [132]:
df_ret.head()

AnoMes,IdCliente,201012,201101,201102,201103,201104,201105,201106,201107,201108,201109,201110,201111,201112
0,12346.0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,12347.0,1,1,0,0,1,0,1,0,1,0,1,0,1
2,12348.0,1,1,0,0,1,0,0,0,0,1,0,0,0
3,12349.0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,12350.0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [133]:
meses = df_ret.columns[2:]
meses

Index([201101, 201102, 201103, 201104, 201105, 201106, 201107, 201108, 201109,
       201110, 201111, 201112],
      dtype='object', name='AnoMes')

In [135]:
lista_ret = []

for i in range(len(meses)-1):
    dados_retencao = {}
    mes_corrente = meses[i+1]
    mes_anterior = meses[i]
    dados_retencao['AnoMes'] = int(mes_corrente)
    dados_retencao['TotalUser'] = df_ret[mes_corrente].sum()
    dados_retencao['TotalRetido'] = df_ret[(df_ret[mes_corrente] > 0) & (df_ret[mes_anterior] > 0)][mes_corrente].sum()
    lista_ret.append(dados_retencao)
    
lista_ret

[{'AnoMes': 201102, 'TotalRetido': 299, 'TotalUser': 798},
 {'AnoMes': 201103, 'TotalRetido': 345, 'TotalUser': 1020},
 {'AnoMes': 201104, 'TotalRetido': 346, 'TotalUser': 899},
 {'AnoMes': 201105, 'TotalRetido': 399, 'TotalUser': 1079},
 {'AnoMes': 201106, 'TotalRetido': 464, 'TotalUser': 1051},
 {'AnoMes': 201107, 'TotalRetido': 415, 'TotalUser': 993},
 {'AnoMes': 201108, 'TotalRetido': 433, 'TotalUser': 980},
 {'AnoMes': 201109, 'TotalRetido': 465, 'TotalUser': 1302},
 {'AnoMes': 201110, 'TotalRetido': 552, 'TotalUser': 1425},
 {'AnoMes': 201111, 'TotalRetido': 690, 'TotalUser': 1711},
 {'AnoMes': 201112, 'TotalRetido': 440, 'TotalUser': 683}]

In [136]:
df_ret_final = pd.DataFrame(lista_ret)
df_ret_final.head()

   AnoMes  TotalUser  TotalRetido
0  201102        798          299
1  201103       1020          345
2  201104        899          346
3  201105       1079          399
4  201106       1051          464

In [141]:
df_ret_final['TaxaRetencao'] = df_ret_final['TotalRetido'] / df_ret_final['TotalUser']
df_ret_final

    AnoMes  TotalUser  TotalRetido  Faturamento  TaxaRetencao
0   201102        798          299     0.374687      0.374687
1   201103       1020          345     0.338235      0.338235
2   201104        899          346     0.384872      0.384872
3   201105       1079          399     0.369787      0.369787
4   201106       1051          464     0.441484      0.441484
5   201107        993          415     0.417925      0.417925
6   201108        980          433     0.441837      0.441837
7   201109       1302          465     0.357143      0.357143
8   201110       1425          552     0.387368      0.387368
9   201111       1711          690     0.403273      0.403273
10  201112        683          440     0.644217      0.644217

In [142]:
plot_data = [go.Scatter(x = df_ret_final.query("AnoMes < 201112")['AnoMes'],
                        y = df_ret_final.query("AnoMes < 201112")['TaxaRetencao'],
                        name = "taxa")]

plot_layout = go.Layout(xaxis = {"type": "category"}, 
                        title = 'Taxa Mensal de Retenção de Clientes')

fig = go.Figure(data = plot_data, layout = plot_layout)
pyoff.iplot(fig)